ΝGramGraphs + Operators 1η Version
ggianna/PyINSECT pull request #1
Opened 2017-05-29 09:59 UTC by ysig

There are one debugging issues we need to solve and further commenting that needs to be added.

2017-05-29 10:28 UTC, ggianna requested changes
Please do the following:
- rename getSimilarity.py to NGramGraphSimilarities.
- Similarity class should extend the BinaryOperator class.
- Let's create test cases (Check Python Unit Testing OPTIONALLY)

2017-05-30 10:31 UTC, ysig commented
Changes added except from unit testing that will
be done consistently on future releases using a
property based testing interface.

2017-05-30 10:36 UTC, ysig commented
Changes have been pushed. Added also code comments. Property Based testing
using the JInsect toolkit as property comparison or extensive unit testing will be created
on a future release.

2017-05-30 11:32 UTC, ggianna approved these changes

2017-05-30 11:33 UTC, merged